In [1]:
import torch
import numpy as np

In [4]:
v = torch.tensor([1,2,3,4,5,6,7,8,9], dtype = torch.float64)

In [5]:
v

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [6]:
v[0], v[2]


(tensor(1., dtype=torch.float64), tensor(3., dtype=torch.float64))

In [7]:
v[-1], v[-2]

(tensor(9., dtype=torch.float64), tensor(8., dtype=torch.float64))

In [9]:
v[1:5]

tensor([2., 3., 4., 5.], dtype=torch.float64)

In [10]:
len(v)

9

In [13]:
u = np.arange(20)
print(u)
u = torch.from_numpy(u)
u

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [14]:
diff = u.sub(u)
diff

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
u = u.numpy()

In [16]:
u


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
fake_img = np.random.random(6*6).reshape(4,9)
fake_img, fake_img.shape[0], fake_img.shape[1]


(array([[0.60226043, 0.75538508, 0.89177645, 0.69168542, 0.04548965,
         0.13137682, 0.15756097, 0.81977584, 0.57223059],
        [0.71089345, 0.57247454, 0.57041779, 0.5988971 , 0.03820188,
         0.2156207 , 0.05389413, 0.34403077, 0.33549732],
        [0.59513446, 0.77671482, 0.8037695 , 0.8314093 , 0.13104017,
         0.01033121, 0.8044413 , 0.39314685, 0.38464609],
        [0.68085623, 0.83994469, 0.15957571, 0.08760624, 0.31437136,
         0.58843937, 0.40537545, 0.83205346, 0.68397031]]),
 4,
 9)

In [44]:
fake_img[2, :]

array([0.59513446, 0.77671482, 0.8037695 , 0.8314093 , 0.13104017,
       0.01033121, 0.8044413 , 0.39314685, 0.38464609])

In [46]:
tensor = torch.rand((5,5,3))
tensor.shape[0], tensor.shape[1], tensor.shape[2]

(5, 5, 3)

In [50]:
# import cv2
# !pip install opencv-python

In [51]:
print(tensor[:,:,2])

tensor([[0.9882, 0.7813, 0.0727, 0.0038, 0.2036],
        [0.0166, 0.8582, 0.9375, 0.9576, 0.4174],
        [0.9206, 0.9966, 0.7165, 0.0600, 0.5021],
        [0.4218, 0.1772, 0.0748, 0.0680, 0.9854],
        [0.6613, 0.0401, 0.1186, 0.7032, 0.6572]])


In [52]:
I49 = torch.stack([torch.arange(0,72,8), torch.arange(64,136,8), torch.arange(128,200,8), torch.arange(192,264,8)])
I49

tensor([[  0,   8,  16,  24,  32,  40,  48,  56,  64],
        [ 64,  72,  80,  88,  96, 104, 112, 120, 128],
        [128, 136, 144, 152, 160, 168, 176, 184, 192],
        [192, 200, 208, 216, 224, 232, 240, 248, 256]])

In [53]:
I49_t = torch.transpose(I49, 0,1)
I49_t

tensor([[  0,  64, 128, 192],
        [  8,  72, 136, 200],
        [ 16,  80, 144, 208],
        [ 24,  88, 152, 216],
        [ 32,  96, 160, 224],
        [ 40, 104, 168, 232],
        [ 48, 112, 176, 240],
        [ 56, 120, 184, 248],
        [ 64, 128, 192, 256]])

In [54]:
I49.shape, I49_t.shape

(torch.Size([4, 9]), torch.Size([9, 4]))

In [55]:
for i in range(I49.shape[0]):
    for j in range(I49.shape[1]):
        assert I49[i][j] == I49_t[j][i]

In [56]:
assert torch.allclose(I49_t, I49.T, 1e-5)


In [57]:
print(I49 * I49)

tensor([[    0,    64,   256,   576,  1024,  1600,  2304,  3136,  4096],
        [ 4096,  5184,  6400,  7744,  9216, 10816, 12544, 14400, 16384],
        [16384, 18496, 20736, 23104, 25600, 28224, 30976, 33856, 36864],
        [36864, 40000, 43264, 46656, 50176, 53824, 57600, 61504, 65536]])


In [58]:
print(I49@ I49.T)

tensor([[ 13056,  31488,  49920,  68352],
        [ 31488,  86784, 142080, 197376],
        [ 49920, 142080, 234240, 326400],
        [ 68352, 197376, 326400, 455424]])


In [59]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
a_dot_b = torch.dot(a,b)
print(a_dot_b)

tensor(32)


In [60]:
print(torch.dot(torch.tensor([1,0]), torch.tensor([0,1])))

tensor(0)


In [61]:
# 15X2, 2X1
W = torch.rand((15,2))
x = torch.rand((2,1))
b = torch.rand((1))
print(W, x,b)

tensor([[0.3516, 0.9959],
        [0.4023, 0.8020],
        [0.6234, 0.5317],
        [0.4893, 0.9097],
        [0.1324, 0.1094],
        [0.8839, 0.4244],
        [0.5514, 0.2416],
        [0.5911, 0.9171],
        [0.5387, 0.5131],
        [0.9097, 0.2442],
        [0.6695, 0.2606],
        [0.8648, 0.9866],
        [0.7641, 0.2720],
        [0.7645, 0.2726],
        [0.7011, 0.2435]]) tensor([[0.4052],
        [0.0593]]) tensor([0.4399])


In [65]:
output = torch.matmul(W,x) + b
print(output)

tensor([[0.6414],
        [0.6504],
        [0.7240],
        [0.6921],
        [0.5000],
        [0.8232],
        [0.6776],
        [0.7338],
        [0.6886],
        [0.8230],
        [0.7266],
        [0.8488],
        [0.7656],
        [0.7658],
        [0.7384]])


In [68]:
I33 = torch.rand((3,3))
J33 = torch.rand((3,3))

assert torch.all(torch.matmul(I33, J33).T == torch.matmul(J33.T, I33.T))

In [69]:
x = torch.rand((3,1))
x

tensor([[0.6414],
        [0.3073],
        [0.9197]])

In [72]:
assert torch.all(torch.matmul(I33.T, x).T == torch.matmul(x.T, I33 ))

In [74]:
def determinant(A):
    return torch.linalg.det(A)

def inverse(A):
    return torch.linalg.inv(A)

I33_inv = inverse(I33)
print(I33_inv)

tensor([[-6.9087,  1.4182,  4.1423],
        [-2.1612, -3.3255,  4.7518],
        [ 8.4794,  1.2393, -6.7742]])


In [75]:
Id_33 = torch.eye(3)
Id_33

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [79]:
A = torch.eye(3)
A_inv = inverse(A)
print(A @ A_inv == Id_33)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [80]:
## Singular Matrix
B = torch.tensor([[1,1], [2,2]])
try: 
    B_inv = inverse(B)
except RuntimeError as e:
    print("The Matrix is not invertible since being the singular".format(B,e))

The Matrix is not invertible since being the singular


In [81]:
def pseudoInverse(A):
    return torch.matmul(inverse(torch.matmul(A.T, A)), A.T)


In [83]:
X = torch.rand((8,2))
X = torch.column_stack((X, torch.ones(8)))
X

tensor([[0.7391, 0.2480, 1.0000],
        [0.4943, 0.5705, 1.0000],
        [0.3284, 0.6235, 1.0000],
        [0.7651, 0.0653, 1.0000],
        [0.6622, 0.1306, 1.0000],
        [0.2745, 0.8792, 1.0000],
        [0.6181, 0.1327, 1.0000],
        [0.4007, 0.1499, 1.0000]])

In [84]:
Y = torch.rand((8,1))
Y

tensor([[0.3762],
        [0.4848],
        [0.5769],
        [0.3147],
        [0.8892],
        [0.3620],
        [0.9431],
        [0.5650]])

In [85]:
W = torch.matmul(pseudoInverse(X), Y)
W

tensor([[-0.6230],
        [-0.5981],
        [ 1.1068]])

In [86]:
from torch import linalg as LA
import math

In [88]:
rot_Z = torch.tensor([[math.cos(45), math.sin(45), 0],[-math.sin(45), math.cos(45), 0],[0,0,1]], dtype = torch.float64)
rot_Z

tensor([[ 0.5253,  0.8509,  0.0000],
        [-0.8509,  0.5253,  0.0000],
        [ 0.0000,  0.0000,  1.0000]], dtype=torch.float64)

In [89]:
l, e = LA.eig(rot_Z)
print(l,e)

tensor([0.5253+0.8509j, 0.5253-0.8509j, 1.0000+0.0000j],
       dtype=torch.complex128) tensor([[0.7071+0.0000j, 0.7071-0.0000j, 0.0000+0.0000j],
        [0.0000+0.7071j, 0.0000-0.7071j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000-0.0000j, 1.0000+0.0000j]],
       dtype=torch.complex128)


In [96]:
print(math.cos(45 * math.pi/180),  1/(math.sqrt(2)))

0.7071067811865476 0.7071067811865475


In [97]:
def cosine(theta):
    return math.cos(theta * math.pi/180)
def sine(theta):
    return math.sin(theta * math.pi/180)


In [98]:
print(cosine(45))

0.7071067811865476


In [115]:
def rotation_matrix_2d(theta):
    return torch.tensor([[cosine(theta), -sine(theta)],[sine(theta), cosine(theta)]], dtype=torch.float)


def rotation_matrix_3d(axis,theta):
    
    if axis==0:
        ## X-axis
        return torch.tensor([[1,0,0],[0, cosine(theta), -sine(theta)],[0, sine(theta), cosine(theta)]], dtype=torch.float)
    
    
    elif axis == 1:
        ## Y-axis
        return torch.tensor([[cosine(theta), 0, -sine(theta)],[0,1,0],[sine(theta), 0, cosine(theta)]], dtype = torch.float)
    
    
    elif axis == 2:
        ## Z-axis
        return torch.tensor([[cosine(theta), -sine(theta), 0],[sine(theta), cosine(theta), 0],[0,0,1]], dtype = torch.float)

    

In [116]:
u = torch.tensor([1,1,1], dtype = torch.float)
u

tensor([1., 1., 1.])

In [117]:
R3dZ = rotation_matrix_3d(2, 45)
R3dZ, R3dZ.shape

(tensor([[ 0.7071, -0.7071,  0.0000],
         [ 0.7071,  0.7071,  0.0000],
         [ 0.0000,  0.0000,  1.0000]]),
 torch.Size([3, 3]))

In [118]:
v = torch.matmul(R3dZ, u)
v

tensor([0.0000, 1.4142, 1.0000])

In [119]:
R_30 = rotation_matrix_2d(30)
R_30

tensor([[ 0.8660, -0.5000],
        [ 0.5000,  0.8660]])

In [120]:
assert torch.allclose(inverse(R_30), R_30.T)

In [121]:
ttt = torch.allclose(inverse(R_30), R_30.T)

In [122]:
ttt

True

In [125]:
x = torch.tensor([1,2], dtype = torch.float)
LA.norm(x)

tensor(2.2361)

In [126]:
y = torch.matmul(R_30, x)
LA.norm(y)

tensor(2.2361)

In [140]:
R3dZ

tensor([[ 0.7071, -0.7071,  0.0000],
        [ 0.7071,  0.7071,  0.0000],
        [ 0.0000,  0.0000,  1.0000]])

In [141]:
l, e = LA.eig(R3dZ)
l, e

(tensor([0.7071+0.7071j, 0.7071-0.7071j, 1.0000+0.0000j]),
 tensor([[ 0.0000-0.7071j,  0.0000+0.7071j,  0.0000+0.0000j],
         [-0.7071+0.0000j, -0.7071-0.0000j,  0.0000+0.0000j],
         [ 0.0000+0.0000j,  0.0000-0.0000j,  1.0000+0.0000j]]))

In [145]:
axis_of_rotation = e[:, torch.where(l==1.)]
axis_of_rotation

tensor([[0.+0.j],
        [0.+0.j],
        [1.+0.j]])

In [146]:
axis_of_rotation = torch.squeeze(axis_of_rotation)
axis_of_rotation

tensor([0.+0.j, 0.+0.j, 1.+0.j])

In [147]:
assert torch.allclose(axis_of_rotation.real, torch.tensor([0,0,1], dtype = torch.float))


In [149]:
p = torch.randint(0,10, (1,)) * axis_of_rotation
assert torch.allclose(torch.matmul(R3dZ, p.real), p.real)

In [152]:
def diagonalize(matrix):
    try:
        l,e = LA.eig(matrix)
        sigma = torch.diag(l)
        return e, sigma, inverse(e)
    except np.linalg.LinAlgError:
        print('Cannot Diagonlize matrix!!')

        
A = R3dZ
S, Sigma, S_inv = diagonalize(A)
print(S, Sigma, S_inv)

tensor([[ 0.0000-0.7071j,  0.0000+0.7071j,  0.0000+0.0000j],
        [-0.7071+0.0000j, -0.7071-0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000-0.0000j,  1.0000+0.0000j]]) tensor([[0.7071+0.7071j, 0.0000+0.0000j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.7071-0.7071j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000+0.0000j, 1.0000+0.0000j]]) tensor([[ 0.0000+0.7071j, -0.7071+0.0000j,  0.0000-0.0000j],
        [ 0.0000-0.7071j, -0.7071+0.0000j,  0.0000-0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  1.0000+0.0000j]])


In [153]:
A1 = torch.matmul(S, torch.matmul(Sigma, S_inv))
A1

tensor([[ 0.7071-2.9802e-08j, -0.7071+0.0000e+00j,  0.0000+0.0000e+00j],
        [ 0.7071+0.0000e+00j,  0.7071+2.9802e-08j,  0.0000+0.0000e+00j],
        [ 0.0000+0.0000e+00j,  0.0000+0.0000e+00j,  1.0000+0.0000e+00j]])

In [157]:
torch.allclose(A, A1.real )

True

In [167]:
A = torch.tensor([[1,2,1],[2,2,3],[1,3,3]], dtype = torch.float)
A

tensor([[1., 2., 1.],
        [2., 2., 3.],
        [1., 3., 3.]])

In [168]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [169]:
b = torch.tensor([8,15,16], dtype = torch.float)
X_0 = torch.matmul(inverse(A), b)
X_0

tensor([1.0000, 2.0000, 3.0000])

In [170]:
w, S = LA.eig(A)
w,S

(tensor([ 6.3485+0.j,  0.7302+0.j, -1.0787+0.j]),
 tensor([[-0.3651+0.j, -0.7759+0.j,  0.5145+0.j],
         [-0.6366+0.j, -0.1953+0.j, -0.7461+0.j],
         [-0.6793+0.j,  0.5999+0.j,  0.4226+0.j]]))

In [173]:
b = torch.tensor(b, dtype = torch.cfloat)
y1 = torch.matmul(S.T, b)
y1

/home/jeet/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([-23.3386+0.j,   0.4624+0.j,  -0.3131+0.j])

In [174]:
y2 = torch.matmul(torch.diag(1/w), y1)

In [175]:
y2

tensor([-3.6762+0.j,  0.6333+0.j,  0.2902+0.j])

In [176]:
x_1 = torch.matmul(S, y2)

In [178]:
x_1

tensor([1.0000+0.j, 2.0000+0.j, 3.0000+0.j])

In [184]:
assert torch.allclose(X_0, x_1.real)

In [192]:
def spectral_decomposition(A):
    assert len(A.shape) == 2 and A.shape[0] == A.shape[1] and torch.all(A == A.T)
    l , e = LA.eig(A)
    
    assert len(torch.unique(l.real)) == A.shape[0]
    C = torch.zeros((A.shape[0], A.shape[0], A.shape[0]))
    
    
    for i, lambda_i in enumerate(l):
        e_i = e[:, i]
        e_i = e_i.reshape((3,1))
        C[i,:,:] = (lambda_i * torch.matmul(e_i, e_i.T)).real
    return C
    
    

In [193]:
A = torch.tensor([[1,2,1], [2,2,3],[1,3,3]]).float()
A

tensor([[1., 2., 1.],
        [2., 2., 3.],
        [1., 3., 3.]])

In [194]:
C = spectral_decomposition(A)
C

tensor([[[ 0.8460,  1.4753,  1.5744],
         [ 1.4753,  2.5726,  2.7454],
         [ 1.5744,  2.7454,  2.9299]],

        [[ 0.4395,  0.1106, -0.3399],
         [ 0.1106,  0.0278, -0.0855],
         [-0.3399, -0.0855,  0.2628]],

        [[-0.2856,  0.4141, -0.2346],
         [ 0.4141, -0.6004,  0.3401],
         [-0.2346,  0.3401, -0.1927]]])

In [195]:
A1 = C.sum(axis = 0)
assert torch.allclose(A, A1)